import type { Category, Product } from './types';
import { fetchProducts, fetchCategories, fetchDistricts } from './services/dataFetching';

// Re-export data fetching functions
export {
  fetchProducts,
  fetchCategories,
  fetchDistricts,
  getCategoryBySlug,
  getCategoryById,
  getProductBySlug,
  getProductsByCategory,
  getFeaturedProducts,
  getDiscountedProducts,
  clearDataCache,
} from './services/dataFetching';

// Keep mock data as fallback for development
export const mockCategories: Category[] = [
  {
    id: 'cat-buket',
    name: 'Buketler',
    slug: 'buketler',
    description: 'El yapımı özel buketler',
    image: 'https://images.pexels.com/photos/931796/pexels-photo-931796.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Flower2',
  },
  {
    id: 'cat-gul',
    name: 'Gül Aranjmanları',
    slug: 'gul-aranjmanlari',
    description: 'Zarif gül kompozisyonları',
    image: 'https://images.pexels.com/photos/1932467/pexels-photo-1932467.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Flower',
  },
  {
    id: 'cat-saksili',
    name: 'Saksılı Bitkiler',
    slug: 'saksili-bitkiler',
    description: 'Uzun ömürlü saksılı çiçekler',
    image: 'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Sprout',
  },
  {
    id: 'cat-ozel',
    name: 'Özel Günler',
    slug: 'ozel-gunler',
    description: 'Doğum günü, yıl dönümü ve daha fazlası',
    image: 'https://images.pexels.com/photos/1580280/pexels-photo-1580280.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Gift',
  },
  {
    id: 'cat-ciceklik',
    name: 'Çiçeklikler',
    slug: 'ciceklikler',
    description: 'Şık çiçeklik ve vazolar',
    image: 'https://images.pexels.com/photos/6243296/pexels-photo-6243296.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Vase',
  },
  {
    id: 'cat-vefat',
    name: 'Vefat Çiçekleri',
    slug: 'vefat-cicekleri',
    description: 'Başsağlığı çiçekleri',
    image: 'https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: 'Heart',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Pembe Rüya Buket',
    slug: 'pembe-ruya-buket',
    categoryId: 'cat-buket',
    price: 549,
    oldPrice: 699,
    images: [
      'https://images.pexels.com/photos/931796/pexels-photo-931796.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/931796/pexels-photo-931796.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Pembe güller, krizantemler ve ölü çiçeklerle özel buket',
    longDescription:
      'Pembe Rüya Buket, taze pembe güller, beyaz krizantemler ve ölü çiçeklerin zarif bir araya getirilmesiyle oluşturulmuş özel bir kompozisyondur. Her çiçek özenle seçilir ve buket ustalarımız tarafından düzenlenir. Aşkınızı, sevginizi ve teşekkürünüzü ifade etmek için mükemmel bir seçim.',
    ingredients: ['12 adet pembe gül', '8 adet beyaz krizantem', '5 adet ölü çiçek', 'Özel buket sargısı'],
    rating: 4.8,
    reviewCount: 124,
    badge: 'Çok Satan',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
    sizes: [
      { id: 's1', name: 'Standart (12 Gül)', priceDifference: 0 },
      { id: 's2', name: 'Orta Boy (18 Gül)', priceDifference: 200 },
      { id: 's3', name: 'Deluxe Boy (24 Gül)', priceDifference: 400 },
    ],
    vases: [
      { id: 'v1', name: 'Vazosuz (Buket Sargılı)', priceDifference: 0 },
      { id: 'v2', name: 'Şeffaf Cam Vazo İle', priceDifference: 120 },
      { id: 'v3', name: 'Şık Seramik Vazo İle', priceDifference: 250 },
    ],
  },
  {
    id: 'p2',
    name: 'Kırmızı Gül Aranjmanı',
    slug: 'kirmizi-gul-aranjmani',
    categoryId: 'cat-gul',
    price: 749,
    images: [
      'https://images.pexels.com/photos/1932467/pexels-photo-1932467.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1932467/pexels-photo-1932467.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: '50 adet kırmızı gül ile görkemli aranjman',
    longDescription:
      'Kırmızı Gül Aranjmanı, 50 adet taze kırmızı gülden oluşan görkemli bir kompozisyondur. Özel cam vazo içinde sunulan bu aranjman, aşkınızı en yoğun şekilde ifade etmek için tasarlandı. Yıl dönümleri, evlilik teklifleri ve romantik özel günler için ideal.',
    ingredients: ['50 adet kırmızı gül', 'Cam vazo', 'Yeşil yaprak aksanları', 'Özel süsleme'],
    rating: 4.9,
    reviewCount: 89,
    badge: 'Çok Satan',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
    sizes: [
      { id: 's1', name: 'Standart (25 Gül)', priceDifference: 0 },
      { id: 's2', name: 'Lüks Boy (50 Gül)', priceDifference: 350 },
      { id: 's3', name: 'Kraliyet Boy (100 Gül)', priceDifference: 850 },
    ],
  },
  {
    id: 'p3',
    name: 'Orkide Saksı',
    slug: 'orkide-saksi',
    categoryId: 'cat-saksili',
    price: 429,
    oldPrice: 529,
    images: [
      'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Beyaz orkide, şık seramik saksıda',
    longDescription:
      'Beyaz Orkide Saksı, uzun ömürlü ve şık bir hediye seçeneğidir. Seramik saksı içinde sunulan beyaz orkide, ev ve ofis mekanlarına zarafet katar. Düşük bakım ihtiyacı ile haftalarca çiçekli kalır.',
    ingredients: ['1 adet beyaz orkide bitkisi', 'Beyaz seramik saksı', 'Bakım talimatı kartı'],
    rating: 4.7,
    reviewCount: 56,
    badge: 'İndirim',
    inStock: true,
    deliveryInfo: '1-2 iş günü teslimat',
    sizes: [
      { id: 's1', name: 'Tek Dal Orkide', priceDifference: 0 },
      { id: 's2', name: 'Çift Dal Orkide', priceDifference: 180 },
    ],
    vases: [
      { id: 'v1', name: 'Standart Plastik Saksı', priceDifference: 0 },
      { id: 'v2', name: 'Beyaz Seramik Saksı', priceDifference: 90 },
      { id: 'v3', name: 'Mermer Desen Saksı', priceDifference: 160 },
    ],
  },
  {
    id: 'p4',
    name: 'Doğum Günü Şenliği',
    slug: 'dogum-gunu-senligi',
    categoryId: 'cat-ozel',
    price: 629,
    images: [
      'https://images.pexels.com/photos/1580280/pexels-photo-1580280.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1580280/pexels-photo-1580280.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Renkli mevsim çiçekleri ve balon ile kutlama seti',
    longDescription:
      'Doğum Günü Şenliği, renkli mevsim çiçekleri ve kutlama balonu ile hazırlanan özel bir kutlama setidir. Sevdiklerinizin doğum gününü unutulmaz kılmak için tasarlandı. Çiçekler, özel kutlama sargısı ile sunulur.',
    ingredients: ['Karışık mevsim çiçekleri', '1 adet kutlama balonu', 'Doğum günü kartı', 'Şenlik sargısı'],
    rating: 4.6,
    reviewCount: 42,
    badge: 'Yeni',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p5',
    name: 'Lilyum Çiçeklik',
    slug: 'lilyum-ciceklik',
    categoryId: 'cat-ciceklik',
    price: 389,
    images: [
      'https://images.pexels.com/photos/6243296/pexels-photo-6243296.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/6243296/pexels-photo-6243296.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Beyaz lilyumlar, cam çiçeklikte',
    longDescription:
      'Lilyum Çiçeklik, beyaz lilyumların cam çiçeklik içinde zarif bir sunumudur. Hoş kokusu ve gösterişli görünümüyle ev ve ofis mekanlarına zarafet katar. Özel davetler ve ziyaretler için ideal bir hediye.',
    ingredients: ['5 adet beyaz lilyum', 'Cam çiçeklik', 'Yeşil yaprak aksanları'],
    rating: 4.5,
    reviewCount: 31,
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
    sizes: [
      { id: 's1', name: 'Standart (5 Dal Lilyum)', priceDifference: 0 },
      { id: 's2', name: 'Büyük Boy (9 Dal Lilyum)', priceDifference: 220 },
    ],
  },
  {
    id: 'p6',
    name: 'Başsağlığı Çelengi',
    slug: 'bassaagliği-celengi',
    categoryId: 'cat-vefat',
    price: 899,
    images: [
      'https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Beyaz karanfillerden başsağlığı çelengi',
    longDescription:
      'Başsağlığı Çelengi, beyaz karanfillerden oluşan geleneksel bir başsağlığı çelengidir. Saygılı ve zarif bir sunum ile sevenlerinizi anmak için tasarlandı. Özel çelenk sargısı ve siyah kurdele ile sunulur.',
    ingredients: ['Beyaz karanfiller', 'Çelenk tabanı', 'Siyah kurdele', 'Saygı sargısı'],
    rating: 4.9,
    reviewCount: 18,
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p7',
    name: 'Lavanta Bahçesi Buket',
    slug: 'lavanta-bahcesi-buket',
    categoryId: 'cat-buket',
    price: 399,
    oldPrice: 499,
    images: [
      'https://images.pexels.com/photos/4013925/pexels-photo-4013925.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/4013925/pexels-photo-4013925.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Lavanta ve beyaz çiçekler ile huzurlu buket',
    longDescription:
      'Lavanta Bahçesi Buket, taze lavantalar ve beyaz çiçeklerin huzurlu bir araya getirilmesiyle oluşturulmuş özel bir bukettir. Hoş kokusu ve pastel renkleriyle sakinleştirici bir etki yaratır. Teşekkür ve geçmiş olsun mesajları için ideal.',
    ingredients: ['15 adet lavanta', '10 adet beyaz çiçek', 'Özel buket sargısı', 'Kuru lavanta aksanı'],
    rating: 4.7,
    reviewCount: 67,
    badge: 'İndirim',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p8',
    name: 'Papatya Neşesi Buket',
    slug: 'papatya-nesesi-buket',
    categoryId: 'cat-buket',
    price: 299,
    images: [
      'https://images.pexels.com/photos/6340978/pexels-photo-6340978.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/6340978/pexels-photo-6340978.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Taze papatyalar ile neşeli buket',
    longDescription:
      'Papatya Neşesi Buket, taze beyaz papatyaların neşeli bir araya getirilmesiyle oluşturulmuş sade ve şık bir bukettir. Safiyeti ve sadeliği ile her ortama neşe katar. Tebrikler, yeni başlangıçlar ve dostluk mesajları için mükemmel.',
    ingredients: ['25 adet beyaz papatya', 'Yeşil yaprak aksanları', 'Doğal buket sargısı'],
    rating: 4.6,
    reviewCount: 93,
    badge: 'Mevsimlik',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p9',
    name: 'Karma Gül Buket',
    slug: 'karma-gul-buket',
    categoryId: 'cat-gul',
    price: 599,
    images: [
      'https://images.pexels.com/photos/1295424/pexels-photo-1295424.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1295424/pexels-photo-1295424.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Pembe, beyaz ve sarı güllerden renkli buket',
    longDescription:
      'Karma Gül Buket, pembe, beyaz ve sarı güllerin renkli bir araya getirilmesiyle oluşturulmuş gösterişli bir bukettir. Çeşitli renklerin uyumu ile her türlü özel gün için uygun. Sevgi, dostluk ve kutlama mesajları için ideal.',
    ingredients: ['10 pembe gül', '10 beyaz gül', '10 sarı gül', 'Özel buket sargısı'],
    rating: 4.8,
    reviewCount: 156,
    badge: 'Çok Satan',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p10',
    name: 'Sukulent Koleksiyonu',
    slug: 'sukulent-koleksiyonu',
    categoryId: 'cat-saksili',
    price: 249,
    oldPrice: 329,
    images: [
      'https://images.pexels.com/photos/10718785/pexels-photo-10718785.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/10718785/pexels-photo-10718785.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: '3 çeşit sukulent, terrarium saksıda',
    longDescription:
      'Sukulent Koleksiyonu, 3 farklı sukulent türünün terrarium saksı içinde sunulduğu modern bir hediye seçeneğidir. Düşük bakım ihtiyacı ve estetik görünümüyle ofis ve ev mekanları için ideal. Uzun ömürlü ve dayanıklı.',
    ingredients: ['3 adet farklı sukulent', 'Terrarium cam saksı', 'Dekoratif taşlar', 'Bakım talimatı'],
    rating: 4.5,
    reviewCount: 44,
    badge: 'İndirim',
    inStock: true,
    deliveryInfo: '1-2 iş günü teslimat',
  },
  {
    id: 'p11',
    name: 'Yıl Dönümü Lüks Buket',
    slug: 'yil-donumu-luks-buket',
    categoryId: 'cat-ozel',
    price: 899,
    oldPrice: 1099,
    images: [
      'https://images.pexels.com/photos/165826/pexels-photo-165826.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/165826/pexels-photo-165826.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Kırmızı güller ve şampanya ile lüks kutlama seti',
    longDescription:
      'Yıl Dönümü Lüks Buket, 25 adet kırmızı gül, şampanya ve çikolata ile hazırlanan görkemli bir kutlama setidir. Yıl dönümlerinizi unutulmaz kılmak için tasarlandı. Lüks sunum kutusu içinde teslim edilir.',
    ingredients: ['25 adet kırmızı gül', '1 şişe şampanya', 'Belgian çikolata', 'Lüks sunum kutusu'],
    rating: 4.9,
    reviewCount: 72,
    badge: 'Çok Satan',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
  {
    id: 'p12',
    name: 'Şakayık Lüks Aranjman',
    slug: 'sakayik-luks-aranjman',
    categoryId: 'cat-ciceklik',
    price: 679,
    images: [
      'https://images.pexels.com/photos/54278/pexels-photo-54278.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/54278/pexels-photo-54278.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    description: 'Pembe şakayıklar, lüks seramik çiçeklikte',
    longDescription:
      'Şakayık Lüks Aranjman, pembe şakayıkların lüks seramik çiçeklik içinde zarif bir sunumudur. Gösterişli çiçekleri ve hoş kokusuyla özel davetler ve ziyaretler için ideal bir hediye. Uzun ömürlü seramik çiçeklik ile kalıcı bir değer.',
    ingredients: ['7 adet pembe şakayık', 'Lüks seramik çiçeklik', 'Yeşil yaprak aksanları'],
    rating: 4.7,
    reviewCount: 38,
    badge: 'Yeni',
    inStock: true,
    deliveryInfo: 'Aynı gün teslimat',
  },
];

// Legacy export for backwards compatibility
export const categories = mockCategories;
export const products = mockProducts;